# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  GOLINT_VERSION: v1.17.1


before_script:
  - cd $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin $GOLINT_VERSION

stages:
  - test

test:
  stage: test
  script:
    - golangci-lint run
    - go vet
    - go test -short
    - go test -race -short
    - go test -msan -short
    - go test -short -covermode=count
