# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  REPO_NAME: gitlab.com/andrewheberle/routerswapper

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

stages:
  - test

test:
  stage: test
  script:
    - golangci-lint run
    - go vet
    - go test -short
    - go test -race -short
    - go test -msan -short
    - go test -short -covermode=count
